'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class Settings1
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings1 = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings1()),Settings1)
    
    Public Shared ReadOnly Property [Default]() As Settings1
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public Property colorStCost() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorStCost"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorStCost") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("255, 255, 128")>  _
    Public Property colorStWork() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorStWork"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorStWork") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("255, 224, 192")>  _
    Public Property colorStGotov() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorStGotov"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorStGotov") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("192, 255, 255")>  _
    Public Property colorStVydan() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorStVydan"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorStVydan") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Gold")>  _
    Public Property colorPaketLam() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorPaketLam"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorPaketLam") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property test() As String
        Get
            Return CType(Me("test"),String)
        End Get
        Set
            Me("test") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property sekin() As Byte
        Get
            Return CType(Me("sekin"),Byte)
        End Get
        Set
            Me("sekin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("111")>  _
    Public Property rrr() As String
        Get
            Return CType(Me("rrr"),String)
        End Get
        Set
            Me("rrr") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("""Services"", ""Design"", ""Materials"", ""PriceCost"", ""PriceGroup"", ""PriceNacenki"", ""Pr"& _ 
        "iceName"", ""PriceParam1"", ""PriceParam2"", ""Reclama""")>  _
    Public Property TablesUniPrice() As String
        Get
            Return CType(Me("TablesUniPrice"),String)
        End Get
        Set
            Me("TablesUniPrice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("PriceServices")>  _
    Public Property TablePriceServices() As String
        Get
            Return CType(Me("TablePriceServices"),String)
        End Get
        Set
            Me("TablePriceServices") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
    Public Property colorRed() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorRed"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorRed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Lime")>  _
    Public Property colorGreen() As Global.System.Drawing.Color
        Get
            Return CType(Me("colorGreen"),Global.System.Drawing.Color)
        End Get
        Set
            Me("colorGreen") = value
        End Set
    End Property
End Class
