kind: Pod
apiVersion: v1
metadata:
 name: fcservice
spec:
 containers:
 - name: fcservice
   image: shersticklock/fcservice:latest
   imagePullPolicy: "IfNotPresent"
   ports:
   - containerPort: 5000